GET http://localhost:8080/api/v1/categories/category/3/update



//update cartitems
//PUT http://localhost:8080/api/v1/cartItems/cart/2/item/1/update?quantity=5

//get cart
//GET http://localhost:8080/api/v1/carts/2/my-cart
 
